MAX_MOVES: int = 400
PLAYGROUND_SIZE: int = 250
CREATURE_COUNT = 500
BRAIN_COMPLEXITY = 1
limit = 20

SCREEN_SIZE = WIDTH, HEIGHT = 1080, 800
COLOR_BLACK = 0, 0, 0
COLOR_WHITE = 255, 255, 255
HORIZONTAL_START, VERTICAL_START = 20, 20

CREATURE_SIZE = 3
HORIZONTAL_END, VERTICAL_END = (
    PLAYGROUND_SIZE * CREATURE_SIZE + HORIZONTAL_START,
    PLAYGROUND_SIZE * CREATURE_SIZE + VERTICAL_START,
)
